title: Peter Byrne Github Pages
description: This is a Github Pages page for Peter Byrne's Generative Design files | N00153868 | Creative Computing.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker